/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Facil;

/*import Geral.imagens */
import javax.swing.ImageIcon;

/**
 *
 * @author Ellen
 */
public class SombrasF extends javax.swing.JFrame {

    /**
     * Creates new form sombras
     */
    public SombrasF() {
        initComponents();
        this.setSize(550, 500);
        //Para quando executar o jogo, a resposta correta nao apareça, e fique só o label com a sombra visivel
        jLabel2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setTitle("TIMB");
        setBackground(new java.awt.Color(51, 255, 255));
        setResizable(false);
        getContentPane().setLayout(null);

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/patopequeno.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(380, 80, 161, 137);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ha.png"))); // NOI18N
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        getContentPane().add(jButton2);
        jButton2.setBounds(180, 80, 161, 137);

        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fa.png"))); // NOI18N
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        getContentPane().add(jButton3);
        jButton3.setBounds(0, 80, 161, 137);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/sombra.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 230, 260, 240);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/parogrande.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(130, 230, 260, 240);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Gimagens/gif claro.gif"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 550, 500);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-566)/2, (screenSize.height-538)/2, 566, 538);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //Quando o botao com a resposta certa foi acionado, o label que contem a sombra irá sumir (false)
        jLabel1.setVisible(false);
        // e o com a resposta aparecer (true)
        jLabel2.setVisible(true);
        //cria um objeto do tipo do Jframe que irá aparecer, no caso a tela Acerto. entao variavel ac do tipo acerto
        /*acerto ac = new acerto();*/
        //quando a resposta certa for acionada, alem de aparecer o label2 , ira aparecer a tela acerto (true)
        /*ac.setVisible(true);*/
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SombrasF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SombrasF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SombrasF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SombrasF.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SombrasF().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
